# Generated by Django 3.0.5 on 2020-12-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201210_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer'),
        ),
    ]
