# Generated by Django 3.1.5 on 2021-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201210_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersanswer',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
