# Generated by Django 3.1.7 on 2021-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210322_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='state',
            field=models.CharField(default='IL', max_length=2),
        ),
    ]
